#!/bin/sh /etc/rc.common
RT=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /root/wol_server.py
    procd_set_param respawn
    procd_close_instance
}
